// Json Mapping Automatically Generated By JsonToolkit Library for C#
// Diego Trinciarelli 2011
// To use this code you will need to reference Newtonsoft's Json Parser, downloadable from codeplex.
// http://json.codeplex.com/
// 
using System;
using Newtonsoft.Json;

namespace Bot.Plugins.Base
{

    [Serializable]
    class SpotifyMetaInfo
    {

        public Info Info;
        public Track[] Tracks;

        //Empty Constructor
        public SpotifyMetaInfo() { }

        public string Serialize()
        {
            return JsonConvert.SerializeObject(this);
        }
        public static SpotifyMetaInfo FromJson(string json)
        {
            return JsonConvert.DeserializeObject<SpotifyMetaInfo>(json);
        }
    }


    [Serializable]
    class Info
    {

        public int NumResults;
        public int Limit;
        public int Offset;
        public string Query;
        public string Type;
        public int Page;

        //Empty Constructor
        public Info() { }

    }


    [Serializable]
    class Availability
    {

        public string Territories;

        //Empty Constructor
        public Availability() { }

    }


    [Serializable]
    class Album
    {

        public string Released;
        public string Href;
        public string Name;
        public Availability Availability;

        //Empty Constructor
        public Album() { }

    }


    [Serializable]
    class ExternalId
    {

        public string Type;
        public string Id;

        //Empty Constructor
        public ExternalId() { }

    }


    [Serializable]
    class Artist
    {

        public string Href;
        public string Name;

        //Empty Constructor
        public Artist() { }

    }


    [Serializable]
    class Track
    {

        public Album Album;
        public string Name;
        public string Popularity;
        public ExternalId[] ExternalIds;
        public double Length;
        public string Href;
        public Artist[] Artists;
        public string TrackNumber;

        //Empty Constructor
        public Track() { }

    }

}
//Json Mapping End
